In [2]:
import numpy as np
from Population import Population
import logging, sys
logging.basicConfig(stream=sys.stderr, level=logging.WARNING)

data = np.genfromtxt("data.csv", delimiter=",")

def fitnessFunc(organism, data):
    weights = np.array(organism.genes)
    weightedData = data * weights
    sumArray = weightedData.sum(axis=1, dtype='float')
    mean = np.mean(sumArray)
    stdev = np.std(sumArray)
    logging.info("data array is %s", data)
    logging.info("weights array is %s", weights)
    logging.info("weighted data is %s", weightedData)
    logging.info("array of sums is %s", sumArray)
    logging.info("stdev of sums is %s", stdev)
    return stdev;

pop = Population(numGenes=5, size=10, matingPool=5, mutationRate=20, fitnessFunc=fitnessFunc, data=data, logger=logging)
pop.orderByFitness()

print "population fitness %s" % pop

pop.churn(10000)

print "population fitness %s" % pop

print "best fitness %s" % pop.getMostFit().fitness
print "best genes: %s" % pop.getMostFit().genes

Data received [[  11.    2.    3.  419.  550.]
 [   1.  234.    3.    4.  550.]
 [   1.    2.   32.  412.  550.]
 [   1.   25.   23.  463.  550.]
 [   1.   29.    3.   48.  550.]]
population fitness [55.3484421441, 64.6131892198, 66.3282592104, 76.3076076358, 82.9629536785, 104.256804214, 122.876879645, 136.714816541, 138.020748078, 157.485728291]
population fitness [0.0391572060292, 0.0391572060292, 0.0391572060292, 0.0391572060292, 0.0391572060292, 0.0391572060292, 32.4088649767, 3.41066418306, 0.0391572060292, 0.0391572060292]
best fitness 0.0391572060292
best genes: [0.0033671315540175772, 0.0006178693272363978, 0.001100387389695201, 0.00016025048127366048, 0.935221199765521]
